[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fully_backed_amm = "AjHF7wsZA9jUp47FYNPfQ2hrwawaNyK7umPUXG9zZb7m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"